version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
      - temp:/app/temp
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    networks:
      - lula-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lula-network

volumes:
  uploads:
  temp:

networks:
  lula-network:
    driver: bridge
